- name: Official SonarQube Scan
  uses: SonarSource/sonarqube-scan-action@v5.2.0
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  with:
    args: >
      -Dsonar.projectKey=PINTUDOS-ARSW_PintudosBack
      -Dsonar.organization=pintando
      -Dsonar.sources=src/main/java
      -Dsonar.tests=src/test/java
      -Dsonar.java.binaries=target/classes
      -Dsonar.host.url=https://sonarcloud.io
