name: Build and SonarQube Analysis (Backend)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project with Maven
        run: mvn clean verify

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: PINTUDOS-ARSW_PintudosBack
          organization: pintando
          extraProperties: |
            sonar.sources=src/main/java
            sonar.tests=src/test/java
            sonar.java.binaries=target/classes
            sonar.sourceEncoding=UTF-8
