name: Backend Build and Test (Sin An치lisis Sonar)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests
        run: mvn clean verify

      # El an치lisis Sonar queda desactivado
      # Si lo quieres habilitar manualmente en el futuro, solo cambia el `if: false` por una condici칩n v치lida
      - name: SonarQube Scan (desactivado)
        if: false
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
